### PR TITLE
Tabs > Spaces

### PR DESCRIPTION
**Pull request by celicoo**
Richard is right! :P

### CODE REVIEW

**Comment by stuartpb** [comment]
Richard is dead-ass wrong. How many spaces are those tabs supposed to expand to, Richard? [Four spaces? _Eight_ spaces? _Three_ spaces?](https://www.youtube.com/watch?v=W_DSOnOQnuk) They compress to the _same damn size_, assuming you know _basic run-length encoding_. You'd think the inventor of middle-out compression would know that.

EDIT: Of course, that's not to say that I condone using _the actual spacebar_ to insert _a whole eight spaces_.

**Comment by joshim5** [comment]
Important change!

**Comment by jjpe** [comment]
The fact most people seem to be missing is that while people usually have a preference for one over the other (mine's spaces - I abhor tabs), ultimately it doesn't matter too much if your editor is a capable one. A capable editor can at the very least hide the details from the programmer. Assuming, of course, that s/he wants it to. If not, ¯\_ _(ツ)_ _/¯

**Comment by aisk** [comment]
we use spaces over tabs, but we use the <kbd>tab</kbd> key to input **four** spaces, but I don't know why @Stitchpunk don't do this, or just she is not using vim or emacs?

**Comment by jjpe** [comment]
Indeed.. 
She said she uses Vim over Emacs, throwing Richard into a hissy fit.

**Comment by stuartpb** [comment]
I'm pretty sure she was just using the spacebar to see if Richard would, in fact, freak out over it, the way she'd been told he would.

That said, say that you're forced to code using something like Nano, where the tab key can only insert tabs. [What do you do?](https://twitter.com/stuartpb/status/737680983927848960)

**Comment by jjpe** [comment]
@stuartpb That's an easy one: usually a *Nix system will not only have nano but also vi(m) and Emacs. So I'll just use one of those.

**Pull request merged**
